In [1]:
%matplotlib inline
import pandas as pd
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [2]:
from sklearn.metrics import classification_report

In [3]:
train_data = pd.read_csv('train.csv')

In [4]:
train_data.head(10)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   
5      0       0       0       0       0       0       0       0       0   
6      7       0       0       0       0       0       0       0       0   
7      3       0       0       0       0       0       0       0       0   
8      5       0       0       0       0       0       0       0       0   
9      3       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   
5       0  ...         0         0         0         0         0         0   
6       0  ...         0         0         0         0         0         0   
7       0  ...         0         0         0         0         0         0   
8       0  ...         0         0         0         0         0         0   
9       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  
5         0         0         0         0  
6         0         0         0         0  
7         0         0         0         0  
8         0         0         0         0  
9         0         0         0         0  

[10 rows x 785 columns]

In [5]:
from sklearn import svm

In [6]:
from sklearn.svm import SVC

In [7]:
y = train_data.label

In [8]:
X = train_data.drop(['label'],axis=1)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [10]:
data_test = pd.read_csv('test.csv')

SVM

In [11]:
model_svc = SVC(decision_function_shape='ovo')
param_grid = {'C': [1, 10, 100, 1000], 'kernel': ['rbf', 'linear']}
# , {'C': [1, 10, 100], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}]
grid_search_cv = GridSearchCV(model_svc, param_grid, cv=5)
grid_search_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(decision_function_shape='ovo'),
             param_grid={'C': [1, 10, 100, 1000], 'kernel': ['rbf', 'linear']})

In [13]:
y_pred = grid_search_cv.predict(X_test)

In [18]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1019    1    2    1    0    0    4    0    2    0]
 [   0 1169    5    2    0    0    3    5    1    0]
 [   3    3 1004    2    2    0    1    5    1    1]
 [   0    2    8 1022    0   11    2    2    8    2]
 [   1    0    2    0 1007    1    0    4    1   11]
 [   2    0    0   10    3  991    5    0    6    4]
 [   4    0    0    0    4    3 1009    0    1    0]
 [   0    1    3    1    3    1    0 1058    0    4]
 [   0    0    0   10    2    5    0    0  987    3]
 [   6    1    0    6   16    1    0    8    0 1022]]
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1029
           1       0.99      0.99      0.99      1185
           2       0.98      0.98      0.98      1022
           3       0.97      0.97      0.97      1057
           4       0.97      0.98      0.98      1027
           5       0.98      0.97      0.97      1021
           6       0.99      0.99      0.99      1021
           7       0.98      0.99   

In [ ]:
grid_search_cv.best_params_

In [ ]:
best_svc = grid_search_cv.best_estimator_

In [ ]:
ypred = best_svc.predict(data_test)

In [27]:
sample_df = pd.read_csv('sample_submission.csv')
output = pd.concat([sample_df.ImageId, pd.DataFrame(ypred)], axis=1)

In [28]:
output.rename(columns={0: "Label"}, inplace=True)

In [29]:
output

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [30]:
output.to_csv('my_submission_03.csv', index=False)